package com.chat.yml.chatxmpp.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.chat.yml.chatxmpp.dao.TblUser;
import com.chat.yml.chatxmpp.dao.TblChat;

import com.chat.yml.chatxmpp.dao.TblUserDao;
import com.chat.yml.chatxmpp.dao.TblChatDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tblUserDaoConfig;
    private final DaoConfig tblChatDaoConfig;

    private final TblUserDao tblUserDao;
    private final TblChatDao tblChatDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tblUserDaoConfig = daoConfigMap.get(TblUserDao.class).clone();
        tblUserDaoConfig.initIdentityScope(type);

        tblChatDaoConfig = daoConfigMap.get(TblChatDao.class).clone();
        tblChatDaoConfig.initIdentityScope(type);

        tblUserDao = new TblUserDao(tblUserDaoConfig, this);
        tblChatDao = new TblChatDao(tblChatDaoConfig, this);

        registerDao(TblUser.class, tblUserDao);
        registerDao(TblChat.class, tblChatDao);
    }
    
    public void clear() {
        tblUserDaoConfig.getIdentityScope().clear();
        tblChatDaoConfig.getIdentityScope().clear();
    }

    public TblUserDao getTblUserDao() {
        return tblUserDao;
    }

    public TblChatDao getTblChatDao() {
        return tblChatDao;
    }

}
