package com.chat.yml.chatxmpp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TBL_CHAT.
 */
public class TblChat {

    private Long id;
    private String jid;
    private String message;
    private String date;
    private String time;
    private Boolean isMine;

    public TblChat() {
    }

    public TblChat(Long id) {
        this.id = id;
    }

    public TblChat(Long id, String jid, String message, String date, String time, Boolean isMine) {
        this.id = id;
        this.jid = jid;
        this.message = message;
        this.date = date;
        this.time = time;
        this.isMine = isMine;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getJid() {
        return jid;
    }

    public void setJid(String jid) {
        this.jid = jid;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Boolean getIsMine() {
        return isMine;
    }

    public void setIsMine(Boolean isMine) {
        this.isMine = isMine;
    }

}
