package com.chat.yml.chatxmpp.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TBL_USER.
 */
public class TblUser {

    private Long id;
    private String userName;
    private String emailId;
    /** Not-null value. */
    private String jid;
    private String name;
    private Integer type;

    public TblUser() {
    }

    public TblUser(Long id) {
        this.id = id;
    }

    public TblUser(Long id, String userName, String emailId, String jid, String name, Integer type) {
        this.id = id;
        this.userName = userName;
        this.emailId = emailId;
        this.jid = jid;
        this.name = name;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    /** Not-null value. */
    public String getJid() {
        return jid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJid(String jid) {
        this.jid = jid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
